version: '3'
services:
  registry:
    image: registry:2
    ports:
      - '5500:5000'
  browser:
    image: mirror.gcr.io/klausmeyer/docker-registry-browser:latest
    environment:
      - 'DOCKER_REGISTRY_URL=http://registry:5000'
    ports:
      - '5580:8080'
